### ISSUE TITLE
不知道为啥不抢

### ISSUE THREAD

**Issue by shizu2014** [wangyiidii/mybti-go#1]
到点了根本没有开始预约...

**Comment by shizu2014** [comment]
huanglundun@ip-192-168-0-103 mybti-go-master % ./mybti-go

                    __    __  _
   ____ ___  __  __/ /_  / /_(_)     ____ _____
  / __ `__ \/ / / / __ \/ __/ /_____/ __ `/ __ \
 / / / / / / /_/ / /_/ / /_/ /_____/ /_/ / /_/ /
/_/ /_/ /_/\__, /_.___/\__/_/      \__, /\____/
          /____/                  /____/
2023/03/30 12:55:17 当前配置如下:
2023/03/30 12:55:17 xxx: 昌平线-沙河站 (0750-0810)
2023/03/30 12:55:17 xxx1: 昌平线-沙河站 (0750-0810)
2023/03/30 12:55:17 任务启动成功, 自动抢票中...
2023/03/30 14:00:00 xxx 的token还有6天失效
2023/03/30 14:00:00 pushplus通知结果:  {"code":200,"msg":"请求成功","data":"2e18b9dba6f14d8e9890cac2fdedaa99","count":null}
2023/03/30 14:00:00 xxx1 的token还有6天失效
2023/03/30 14:00:00 pushplus通知结果:  {"code":200,"msg":"请求成功","data":"67bedac26d7b45d48b0e2461a2680938","count":null}
^C2023/03/30 20:00:20 自动抢票已停止

**Comment by shizu2014** [comment]
根本不开始抢。。。

**Comment by zzzgr** [comment]
> 根本不开始抢。。。

我今天都可以抢
![IMG_1991](https://github.com/wangyiidii/mybti-go/assets/32561537/984dabb1-d039-4d93-bf2f-46987ba29ee9)
![be5904b176f5bc1890df73eccabd4a9f](https://github.com/wangyiidii/mybti-go/assets/32561537/fccaf6fc-f170-4d82-9083-da5aaacae1ae)

```
   ____ ___  __  __/ /_  / /_(_)     ____ _____ 
  / __ `__ \/ / / / __ \/ __/ /_____/ __ `/ __ \
 / / / / / / /_/ / /_/ / /_/ /_____/ /_/ / /_/ /
/_/ /_/ /_/\__, /_.___/\__/_/      \__, /\____/ 
          /____/                  /____/        
2023/11/29 11:15:31 当前配置如下: 
2023/11/29 11:15:31 账号 1: 5号线-天通苑站 (0630-0640)
2023/11/29 11:15:31 账号 2: 昌平线-沙河站 (0800-0810)
2023/11/29 11:15:31 任务启动成功, 自动抢票中...
2023/11/29 12:00:00 20231130, 抢票
2023/11/29 12:00:00 账号 2 开始抢票
2023/11/29 12:00:00 账号 2 第1次抢票
2023/11/29 12:00:00 账号 1 开始抢票
2023/11/29 12:00:00 账号 1 第1次抢票
2023/11/29 12:00:03 账号 2 第1次抢票，原始响应: {"balance":0,"appointmentId":"","stationEntrance":""}
2023/11/29 12:00:03 账号 2 第2次抢票
2023/11/29 12:00:03 账号 1 第1次抢票，原始响应: {"balance":-1,"appointmentId":"","stationEntrance":""}
2023/11/29 12:00:03 账号 1 第2次抢票
2023/11/29 12:00:06 账号 2 第2次抢票，原始响应: {"balance":6,"appointmentId":"******","stationEntrance":"A2口"}
2023/11/29 12:00:06 账号 2抢票成功 
 线路: 昌平线-沙河站 
 进站时间: 0800-0810 
 进站口: A2口 
 抢票次数: 2
2023/11/29 12:00:06 pushplus通知结果:  {"code":200,"msg":"请求成功","data":"******","count":null}
2023/11/29 12:00:06 账号 1 第2次抢票，原始响应: {"balance":-1,"appointmentId":"","stationEntrance":""}
2023/11/29 12:00:06 账号 1 第3次抢票
2023/11/29 12:00:10 账号 1 第3次抢票，原始响应: {"balance":46,"appointmentId":"******","stationEntrance":"B口优检通道"}
2023/11/29 12:00:10 账号 1抢票成功 
 线路: 5号线-天通苑站 
 进站时间: 0630-0640 
 进站口: B口优检通道 
 抢票次数: 3
2023/11/29 12:00:10 pushplus通知结果:  {"code":200,"msg":"请求成功","data":"******","count":null}
```
